import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import axios from 'axios';
import { useState, useEffect } from 'react';

const BUCKET_URL =
	'https://products-mighty-images.s3.ap-southeast-1.amazonaws.com';

export default function Home() {
	const [file, setFile] = useState();
	const [uploadingStatus, setUploadingStatus] = useState();
	const [uploadedFile, setUploadedFile] = useState('');
	const [items, setItems] = useState([]);

	useEffect(() => {
		const fetchItems = async () => {
			const {
				data: { data }
			} = await axios.get('/api/items');
			console.log(data);
			setItems(data);
		};
		fetchItems();
	}, []);

	const selectFile = (e) => {
		console.log(e.target.files[0]);
		setFile(e.target.files[0]);
	};

	function hasWhiteSpace(s) {
		return /\s/g.test(s);
	}

	const uploadFile = async () => {
		setUploadingStatus('Uploading the file to AWS S3');

		let { data } = await axios.post(
			'/api/upload-file-s3',
			{
				name: file.name,
				type: file.type
			},
			{
				headers: {
					'Access-Control-Allow-Origin': '*'
				}
			}
		);

		const url = data.url;

		setUploadedFile(`${BUCKET_URL}/${fileName}`);

		console.log(url);

		const productTitle = `Product ${String(Math.random())}`;
		const stringifyName = String(file.name);
		console.log(stringifyName);
		const fileName = hasWhiteSpace(stringifyName)
			? stringifyName.replace(/ /g, '%20')
			: stringifyName;

		// add data to mongodb
		const newItems = await axios.post('/api/items', {
			title: productTitle,
			image: `${BUCKET_URL}/${fileName}`
		});
		console.log(newItems);

		console.log(`${BUCKET_URL}/${fileName}`);

		await axios
			.put(url, file, {
				headers: {
					'Content-type': String(file.type),
					'Access-Control-Allow-Origin': '*'
				}
			})
			.then(() => {
				setItems([
					...items,
					{
						title: productTitle,
						image: `${BUCKET_URL}/${fileName}`
					}
				]);
			});
	};

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1>NextJs AWS-S3 MongoDB</h1>
				<h2>Hope the upload is super fast</h2>
				<br />
				<input type="file" onChange={selectFile} />
				<br />
				{file && <button onClick={uploadFile}>Upload</button>}
				<br />
				{items?.map((item, idx) => (
					<div key={idx}>
						<h3>{item.title}</h3>
						<Image src={item.image} alt="..." width={300} height={300} />
					</div>
				))}
			</main>
		</div>
	);
}
